---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPU-Z80-Assembler
no_index:
  directory:
    - t
    - inc
requires:
  Asm::Preproc: 1
  Asm::Z80::Table: 0.02
  Class::Struct: 0
  Data::Dump: 1.08
  File::Slurp: 9999.13
  File::Spec: 0
  Iterator::Array::Jagged: 0.05
  Iterator::Simple::Lookahead: 0.04
  Regexp::Trie: 0.02
  Test::More: 0.96
  Text::Tabs: 2006.1117
version: 2.14
