--- #YAML:1.0
name:               CPU-Z80-Assembler
version:            2.08_01
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Struct:  0
    Data::Dump:     1.08
    File::Slurp:    9999.13
    File::Spec:     0
    Regexp::Trie:   0.02
    Test::More:     0
    Text::Tabs:     2006.1117
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
